## Treinamento e teste dos modelos "svm" e "linear_model" <br>
Testes e análise de resultado dos modelos

In [1]:
#Import das bibliotecas ultilizadas
import dlib
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
#%matplotlib inline

In [2]:
#Abrindo os arquivos com os dados base coletados anteriormente.
dataframeDormindo = pd.read_csv('Base_Dormindo.cvs')
dataframeNormal   = pd.read_csv('Base_Normal.cvs')

In [3]:
dataframeNormal.columns = dataframeDormindo.columns

In [ ]:
#APAGAR COLUNA
    #dataframeDormindo.drop('Unnamed: 0', inplace=True, axis=1)
#Adiciona coluna tag
    #dataframeDormindo['tag'] = "dormindo"
    #dataframeDormindo

#____________________________________________________________________
#____________________________________________________________________

#APAGAR COLUNA
    #dataframeNormal.drop('Unnamed: 0', inplace=True, axis=1) 
#Adiciona coluna tag
    #dataframeNormal['tag'] = "normal"
    #dataframeNormal

In [ ]:
#Salvar os dados sem considerar o index
    #dataframeDormindo.to_csv("Base_Dormindo.cvs",index=False)
    #dataframeNormal.to_csv("Base_Normal.cvs",index=False)

In [4]:
#data frame "dataTeste" recebe as base de dados
dataTeste = dataframeDormindo.append(dataframeNormal, ignore_index=True) 

In [5]:
#Embaralhamos as linhas para os dados não ficarem alinhados
dataTeste = dataTeste.reindex(np.random.permutation(dataTeste.index))
dataTeste = dataTeste.reset_index(drop=True)

## Treinar os modelos

In [6]:
#Import da biblioteca e do modulo para dividir os dados para teste e para treianmento
from sklearn.model_selection import train_test_split

In [7]:
#Separando os dados

#Retirando a coluna "tag" e salvando
X = dataTeste.drop('tag',axis=1)
#Cria a coluna novamente porém sem os dados
y = dataTeste['tag']
#Separamos os dados e definimos 30% de dados para teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [48]:
#import da biblioteca e dos modulos dos modelos para treinamento
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
#from xgboost import XGBRegressor
from xgboost import XGBClassifier

In [49]:
#Definimos as variavis para os modelos
svc_model = SVC()
lr_model = LogisticRegression()
#xgbr_model = XGBRegressor(gamma='scale')
xgbr_model = XGBClassifier()

In [50]:
#Trinando os modelos

#Passamos pasamos os dados com "resposta" para treinar os modelos
svc_model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [51]:
lr_model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [52]:
xgbr_model.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

## Avaliar o modelo

Matriz de Confusão e Relatório de Classificação.

In [53]:
#Enviando os dados para o modelo de previsão para testar e pegando o resultado nas variaveis
svc_predictions = svc_model.predict(X_test)
lr_predictions = lr_model.predict(X_test)
xgbr_predictions = xgbr_model.predict(X_test)

In [54]:
#Importando a biblioteca com os modulos de report e matriz de confusão
from sklearn.metrics import classification_report,confusion_matrix

In [55]:
#Imprimindo a matriz de confusão passando os dados de teste com os resultados obtidos pelo modelo
print(confusion_matrix(y_test,svc_predictions))
print(confusion_matrix(y_test,lr_predictions))
print(confusion_matrix(y_test,xgbr_predictions))

[[13  6]
 [ 2 13]]
[[16  3]
 [ 2 13]]
[[19  0]
 [ 2 13]]


In [56]:
#Imprimindo o modelo passando os dados de teste com os resultados obtidos pelo modelo
print(classification_report(y_test,svc_predictions))
print(classification_report(y_test,lr_predictions))
print(classification_report(y_test,xgbr_predictions))

              precision    recall  f1-score   support

    dormindo       0.87      0.68      0.76        19
      normal       0.68      0.87      0.76        15

    accuracy                           0.76        34
   macro avg       0.78      0.78      0.76        34
weighted avg       0.79      0.76      0.76        34

              precision    recall  f1-score   support

    dormindo       0.89      0.84      0.86        19
      normal       0.81      0.87      0.84        15

    accuracy                           0.85        34
   macro avg       0.85      0.85      0.85        34
weighted avg       0.86      0.85      0.85        34

              precision    recall  f1-score   support

    dormindo       0.90      1.00      0.95        19
      normal       1.00      0.87      0.93        15

    accuracy                           0.94        34
   macro avg       0.95      0.93      0.94        34
weighted avg       0.95      0.94      0.94        34



## Versão Bibliotecas

In [ ]:
pip list